logging:
    level:
        org:
            hibernate:
                sql: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
            springframework:
                http:
                    client:
                        HttpComponentsClientHttpRequestFactory: DEBUG
                web:
                    client:
                        RestTemplate: DEBUG
server:
    port: 8082
spring:
    application:
        name: Transaction-service
    datasource:
        driver-class-name: org.postgresql.Driver
        password: aishnapathak
        url: jdbc:postgresql://localhost:5432/transaction
        username: aishnapathak
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    security:
        user:
            name: ${USER_NAME:user}
            password: ${USER_PASSWORD:defaultPassword}
user-service:
    auth:
        password: aishnapathak
        username: aishnapathak
    base-url: http://localhost:8080
