server:
    port: 8081
spring:
    application:
        name: AI-service
    ai:
      ollama:
        base-url: http://localhost:11434
        chat:
          options:
            model: mistral
            temperature: 0.7
    datasource:
      driver-class-name: org.postgresql.Driver
      password: aishnapathak
      url: jdbc:postgresql://localhost:5432/transaction
      username: aishnapathak
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
      show-sql: true