spring:
    application:
        name: User-service
    datasource:
        password: aishnapathak
        url: jdbc:postgresql://localhost:5432/user_db
        username: aishnapathak
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    security:
        user:
            name: ${USER_NAME:user} # Default to "user" if the environment variable is not set
            password: ${USER_PASSWORD:defaultPassword} # Default to "defaultPassword" if the environment variable is not set
logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
